### ISSUE TITLE
Error on boot, Ionicons is not a system font.

### ISSUE THREAD

**Issue by jswhisperer** [Haakh/react-native-mobx-feathers#1]
![image](https://user-images.githubusercontent.com/1177690/29943866-286f0bd6-8e69-11e7-9f0d-a90f4b338e9d.png)

**Comment by Haakh** [comment]
@gregbenner  Can you check the latest code and confirm if the issue still persists? sorry for the late reply.

**Comment by jswhisperer** [comment]
No worries, fixed! thank you
