### ISSUE TITLE
Feature Request: Example /Services

### ISSUE THREAD

**Issue by jswhisperer** [Haakh/react-native-mobx-feathers#2]
Would it be possible to add the services folder and a couple examples how mobx async fetches might be done? As per the article https://blog.geekyants.com/structuring-a-react-native-mobx-application-the-right-way-c1e9d2ae0ff7

**Comment by Haakh** [comment]
Yes, that's in the TODO. Will do it in a couple of days with a working feathers server.

**Comment by jswhisperer** [comment]
Thank you!
